
apiVersion: v1
kind: Service
metadata:
  name: pvtest-watcher
  labels:
    app: pvtest
    component: watcher
spec:
  type: NodePort
  ports:
  - port: 8000
    name: web
  selector:
    app: pvtest
    component: watcher
