
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-ozone
subjects:
- kind: ServiceAccount
  name: csi-ozone
  namespace: default
roleRef:
  kind: ClusterRole
  name: csi-ozone
  apiGroup: rbac.authorization.k8s.io
