
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ozone-scm
  labels:
    app: ozone
    component: scm
spec:
  selector:
    matchLabels:
      app: ozone
      component: scm
  serviceName: ozone-scm
  replicas: 1
  template:
    metadata:
      labels:
        app: ozone
        component: scm
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9876"
        prometheus.io/path: /prom
    spec:
      initContainers:
      - name: init
        image: elek/ozone-dev:be8a2fcc8
        args:
        - ozone
        - scm
        - --init
        volumeMounts:
        - name: data
          mountPath: /data
        - name: ozone-dev
          mountPath: /opt/ozone
        envFrom:
        - configMapRef:
            name: ozone-config
      containers:
      - name: scm
        image: elek/ozone-dev:be8a2fcc8
        args:
        - ozone
        - scm
        volumeMounts:
        - name: data
          mountPath: /data
        - name: ozone-dev
          mountPath: /opt/ozone
        envFrom:
        - configMapRef:
            name: ozone-config
      volumes:
      - name: data
        emptyDir: {}
      - name: ozone-dev
        hostPath:
          path: /home/elek/projects/ozone/hadoop-ozone/dist/target/ozone-0.6.0-SNAPSHOT/
