
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ozone-s3g
  labels:
    app: ozone
    component: s3g
spec:
  selector:
    matchLabels:
      app: ozone
      component: s3g
  serviceName: ozone-s3g
  replicas: 1
  template:
    metadata:
      labels:
        app: ozone
        component: s3g
    spec:
      containers:
      - name: s3g
        image: flokkr/ozone@sha256:74abe1431ea2e636de9f769a23278a385d1b09cb4f93fe870d375fa4bfb80f1f
        args:
        - ozone
        - s3g
        volumeMounts:
        - name: data
          mountPath: /data
        - name: smoketest
          mountPath: /opt/smoketest
        envFrom:
        - configMapRef:
            name: ozone-config
      volumes:
      - name: data
        emptyDir: {}
      - name: smoketest
        hostPath:
          path: /home/elek/projects/flokkr/docker-ozone/examples/simple/smoketest
