
apiVersion: v1
kind: Secret
metadata:
  name: ozone-datanode-keytabs
data:
  dn.keytab: BQIAAABIAAIAC0VYQU1QTEUuQ09NAAJkbgACZG4AAAABXrg5wQQAEgAg9TFCyAsefRnzIecZyb3aqx0dsS8IMWnZzAlYCWsCD+cAAAAEAAAAOAACAAtFWEFNUExFLkNPTQACZG4AAmRuAAAAAV64OcEEABEAEIHw1NkJTdG4c+hwJRmb+hgAAAAE
  HTTP.keytab: BQIAAABKAAIAC0VYQU1QTEUuQ09NAARIVFRQAAJkbgAAAAFeuDnCBAASACDAhZVUf3FX7rc23qYrT/LpK21I0yVwa2dFsQtKCYS0sgAAAAQAAAA6AAIAC0VYQU1QTEUuQ09NAARIVFRQAAJkbgAAAAFeuDnCBAARABAhHJTOYnqmqZ4EMKwFWdvfAAAABA==
