
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ozone-scm
  labels:
    app: ozone
    component: scm
spec:
  selector:
    matchLabels:
      app: ozone
      component: scm
  serviceName: ozone-scm
  replicas: 1
  template:
    metadata:
      labels:
        app: ozone
        component: scm
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9876"
        prometheus.io/path: /prom
    spec:
      initContainers:
      - name: init
        image: flokkr/ozone@sha256:74abe1431ea2e636de9f769a23278a385d1b09cb4f93fe870d375fa4bfb80f1f
        args:
        - ozone
        - scm
        - --init
        volumeMounts:
        - name: data
          mountPath: /data
        - name: keytabs
          mountPath: /etc/security/keytabs
        - name: krb5conf
          mountPath: /etc/krb5.conf
          subPath: krb5.conf
        envFrom:
        - configMapRef:
            name: ozone-config
      containers:
      - name: scm
        image: flokkr/ozone@sha256:74abe1431ea2e636de9f769a23278a385d1b09cb4f93fe870d375fa4bfb80f1f
        args:
        - ozone
        - scm
        volumeMounts:
        - name: data
          mountPath: /data
        - name: keytabs
          mountPath: /etc/security/keytabs
        - name: krb5conf
          mountPath: /etc/krb5.conf
          subPath: krb5.conf
        envFrom:
        - configMapRef:
            name: ozone-config
      volumes:
      - name: data
        emptyDir: {}
      - name: keytabs
        secret:
          secretName: ozone-scm-keytabs
      - name: krb5conf
        configMap:
          name: krb5-conf
