
apiVersion: v1
kind: Secret
metadata:
  name: ozone-om-keytabs
data:
  om.keytab: |
    BQIAAABzAAIAC0VYQU1QTEUuQ09NAAJvbQAtb3pvbmUtb20tMC5vem9uZS1vbS5kZWZhdWx0LnN2
    Yy5jbHVzdGVyLmxvY2FsAAAAAV62jdgCABIAICY0QjSFfxPpI041nWVW8ZJgD8XkPhKbMf8UTf/D
    RcrNAAAAAgAAAGMAAgALRVhBTVBMRS5DT00AAm9tAC1vem9uZS1vbS0wLm96b25lLW9tLmRlZmF1
    bHQuc3ZjLmNsdXN0ZXIubG9jYWwAAAABXraN2AIAEQAQfwPnJccC/JrhsdIcyVYOOQAAAAI=
  HTTP.keytab: |
    BQIAAAB1AAIAC0VYQU1QTEUuQ09NAARIVFRQAC1vem9uZS1vbS0wLm96b25lLW9tLmRlZmF1bHQu
    c3ZjLmNsdXN0ZXIubG9jYWwAAAABXraN2AIAEgAgoKfVBivTtTKJ1HIkCW5f8wIQBymWhborKzIw
    qm8+0+cAAAACAAAAZQACAAtFWEFNUExFLkNPTQAESFRUUAAtb3pvbmUtb20tMC5vem9uZS1vbS5k
    ZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsAAAAAV62jdgCABEAEJKbhfDVwoSVA9WibDA+Rd0AAAAC
