
apiVersion: v1
kind: Secret
metadata:
  name: ozone-om-keytabs
data:
  om.keytab: |
    BQIAAABzAAIAC0VYQU1QTEUuQ09NAAJvbQAtb3pvbmUtb20tMC5vem9uZS1vbS5kZWZhdWx0LnN2
    Yy5jbHVzdGVyLmxvY2FsAAAAAV6uwKkDABIAICXM5X33yzy+ZtBNm3bflFLl88tMPqyn+TrgXsqB
    bK7gAAAAAwAAAGMAAgALRVhBTVBMRS5DT00AAm9tAC1vem9uZS1vbS0wLm96b25lLW9tLmRlZmF1
    bHQuc3ZjLmNsdXN0ZXIubG9jYWwAAAABXq7AqQMAEQAQ6X7BK5Cz0bHb1dOo7vtRqAAAAAM=
  HTTP.keytab: |
    BQIAAAB1AAIAC0VYQU1QTEUuQ09NAARIVFRQAC1vem9uZS1vbS0wLm96b25lLW9tLmRlZmF1bHQu
    c3ZjLmNsdXN0ZXIubG9jYWwAAAABXq7AqgMAEgAgcrzQupZ9gpVkXY0kgay9rnDqoEA6oAYjah5W
    2oCMXAIAAAADAAAAZQACAAtFWEFNUExFLkNPTQAESFRUUAAtb3pvbmUtb20tMC5vem9uZS1vbS5k
    ZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsAAAAAV6uwKoDABEAEFa4hobKb6uI6dnhc7vql4sAAAAD
