
apiVersion: v1
kind: Secret
metadata:
  name: ozone-scm-keytabs
data:
  scm.keytab: |
    BQIAAAB2AAIAC0VYQU1QTEUuQ09NAANzY20AL296b25lLXNjbS0wLm96b25lLXNjbS5kZWZhdWx0
    LnN2Yy5jbHVzdGVyLmxvY2FsAAAAAV62scgEABIAIJbUTD5+Td10g/ZzLhCJ2GFWvUDqpnX9rW6v
    2gYJm3QKAAAABAAAAGYAAgALRVhBTVBMRS5DT00AA3NjbQAvb3pvbmUtc2NtLTAub3pvbmUtc2Nt
    LmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwAAAABXraxyAQAEQAQpQDHhzmPoZlA+VkFbz7NsQAA
    AAQ=
  HTTP.keytab: |
    BQIAAAB3AAIAC0VYQU1QTEUuQ09NAARIVFRQAC9vem9uZS1zY20tMC5vem9uZS1zY20uZGVmYXVs
    dC5zdmMuY2x1c3Rlci5sb2NhbAAAAAFetrHJBAASACC8eyblsDSqGULMb2g/U7TP2FXN5XyAgSZw
    QQtWyRakXgAAAAQAAABnAAIAC0VYQU1QTEUuQ09NAARIVFRQAC9vem9uZS1zY20tMC5vem9uZS1z
    Y20uZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbAAAAAFetrHJBAARABD06fIDuZ7O8wzrcJXIdrbN
    AAAABA==
  test.keytab: |
    BQIAAABPAAIAC0VYQU1QTEUuQ09NAAh0ZXN0dXNlcgADc2NtAAAAAV62scoEABIAIPcK+2Hy1Kz2
    /B7lEgC2uXbQCefaNd05oOHzUYyDhk44AAAABAAAAD8AAgALRVhBTVBMRS5DT00ACHRlc3R1c2Vy
    AANzY20AAAABXraxygQAEQAQDU7G3HiQFsOaNLn4HkGSagAAAAQ=
