
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ozone-datanode
  labels:
    app: ozone
    component: datanode
spec:
  selector:
    matchLabels:
      app: ozone
      component: datanode
  serviceName: ozone-datanode
  replicas: 3
  template:
    metadata:
      labels:
        app: ozone
        component: datanode
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9882"
        prometheus.io/path: /prom
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: datanode
        image: flokkr/ozone@sha256:74abe1431ea2e636de9f769a23278a385d1b09cb4f93fe870d375fa4bfb80f1f
        args:
        - ozone
        - datanode
        volumeMounts:
        - name: data
          mountPath: /data
        - name: keytabs
          mountPath: /etc/security/keytabs
        - name: krb5conf
          mountPath: /etc/krb5.conf
          subPath: krb5.conf
        - name: smoketest
          mountPath: /opt/smoketest
        envFrom:
        - configMapRef:
            name: ozone-config
      volumes:
      - name: data
        emptyDir: {}
      - name: keytabs
        secret:
          secretName: ozone-datanode-keytabs
      - name: krb5conf
        configMap:
          name: krb5-conf
      - name: smoketest
        hostPath:
          path: /home/elek/projects/flokkr/docker-ozone/examples/smoketest
