
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ozone-s3g
  labels:
    app: ozone
    component: s3g
spec:
  selector:
    matchLabels:
      app: ozone
      component: s3g
  serviceName: ozone-s3g
  replicas: 1
  template:
    metadata:
      labels:
        app: ozone
        component: s3g
    spec:
      containers:
      - name: s3g
        image: flokkr/ozone@sha256:74abe1431ea2e636de9f769a23278a385d1b09cb4f93fe870d375fa4bfb80f1f
        args:
        - ozone
        - s3g
        volumeMounts:
        - name: data
          mountPath: /data
        - name: ozone-dev
          mountPath: /opt/ozone
        - name: keytabs
          mountPath: /etc/security/keytabs
        - name: krb5conf
          mountPath: /etc/krb5.conf
          subPath: krb5.conf
        - name: ssl
          mountPath: /etc/ssl
        envFrom:
        - configMapRef:
            name: ozone-config
      volumes:
      - name: data
        emptyDir: {}
      - name: ozone-dev
        hostPath:
          path: /home/elek/projects/ozone/hadoop-ozone/dist/target/ozone-0.6.0-SNAPSHOT
      - name: keytabs
        secret:
          secretName: ozone-s3g-keytabs
      - name: krb5conf
        configMap:
          name: krb5-conf
      - name: ssl
        secret:
          secretName: ozone-s3g-keystore
